### PR TITLE
[v2] buildAll.sh: Add the installation

### PR DESCRIPTION
**Pull request by jiazhang0**
Otherwise, the include dirs and header files cannot be found by
dependent components.

Signed-off-by: Jia Zhang <qianyue.zj@alibaba-inc.com>

### CODE REVIEW

**Comment by hq6** [comment]
Thanks for this PR!

Can you please exclude the directories `ArachnePerfTests arachne-sosp2017-benchmarks` from the `make install` command? Otherwise, these commands will fail and possibly confuse other users.

**Comment by jiazhang0** [comment]
I submitted commits for ArachnePerfTests and arachne-sosp2017-benchmarks to add install rule. If you think they are not necessary, I will change to bypass them in buildAll.sh. Plz let me know your opinion.

**Comment by hq6** [comment]
Please bypass `install` in `ArachnePerfTests` only. I've merged your PR on `arachne-sosp2017-benchmarks`, although that repository will likely be refactored / cleaned up at some point in the near future.

**Comment by jiazhang0** [comment]
@hq6 V2 PR was sent.

**Review by hq6 — APPROVED** [review]

**Pull request merged**
